=== scikit-hep/uhi/src/uhi/resources/histogram.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/scikit-hep/uhi/main/src/uhi/resources/histogram.schema.json",
  "title": "Histogram",
  "description": "A single histogram, the intermediate representation (IR). See histograms.schema.json for the JSON file format.",
  "type": "object",
  "required": ["uhi_schema", "axes", "storage"],
  "additionalProperties": false,
  "properties": {
    "uhi_schema": {
      "const": 1,
      "description": "The schema version number"
    },
    "writer_info": { "$ref": "#/$defs/writer_info" },
    "metadata": { "$ref": "#/$defs/metadata" },
    "axes": {
      "type": "array",
      "description": "A list of the axes of the histogram.",
      "items": {
        "oneOf": [
          { "$ref": "#/$defs/regular_axis" },
          { "$ref": "#/$defs/variable_axis" },
          { "$ref": "#/$defs/category_str_axis" },
          { "$ref": "#/$defs/category_int_axis" },
          { "$ref": "#/$defs/boolean_axis" }
        ]
      }
    },
    "storage": {
      "description": "The storage of the bins of the histogram.",
      "oneOf": [
        { "$ref": "#/$defs/int_storage" },
        { "$ref": "#/$defs/double_storage" },
        { "$ref": "#/$defs/weighted_storage" },
        { "$ref": "#/$defs/mean_storage" },
        { "$ref": "#/$defs/weighted_mean_storage" }
      ]
    }
  },
  "$defs": {
    "supported_metadata": {
      "oneOf": [
        { "type": "string" },
        { "type": "number" },
        { "type": "boolean" }
      ]
    },
    "metadata": {
      "type": "object",
      "description": "Arbitrary metadata dictionary.",
      "additionalProperties": false,
      "patternProperties": {
        ".+": { "$ref": "#/$defs/supported_metadata" }
      }
    },
    "writer_info": {
      "type": "object",
      "description": "Information from the library that created the histogram.",
      "additionalProperties": false,
      "patternProperties": {
        ".+": {
          "type": "object",
          "description": "Library specific information.",
          "additionalProperties": false,
          "patternProperties": {
            ".+": { "$ref": "#/$defs/supported_metadata" }
          }
        }
      }
    },
    "ndarray": {
      "type": "array",
      "items": {
        "oneOf": [{ "type": "number" }, { "$ref": "#/$defs/ndarray" }]
      },
      "description": "A ND (nested) array of numbers."
    },
    "int_ndarray": {
      "type": "array",
      "items": {
        "oneOf": [{ "type": "integer" }, { "$ref": "#/$defs/int_ndarray" }]
      },
      "description": "A ND (nested) array of integers."
    },
    "int_data_array": {
      "oneOf": [
        {
          "type": "string",
          "description": "A path (similar to URI) to the integer bin data"
        },
        {
          "$ref": "#/$defs/int_ndarray"
        },
        {
          "type": "integer",
          "description": "A single integer, for a histogram with no axes"
        }
      ]
    },
    "data_array": {
      "oneOf": [
        {
          "type": "string",
          "description": "A path (similar to URI) to the floating point bin data"
        },
        {
          "$ref": "#/$defs/ndarray"
        },
        {
          "type": "number",
          "description": "A single number, for a histogram with no axes"
        }
      ]
    },
    "sparse_array": {
      "oneOf": [
        {
          "type": "string",
          "description": "A path (similar to URI) to the index data"
        },
        {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "integer",
              "description": "Bin indexes, 0 is the underflow if present"
            },
            "description": "A 2D array of integers."
          },
          "description": "The 2D index array, outer dimension is axis number, inner matches the 1D data."
        }
      ]
    },
    "regular_axis": {
      "type": "object",
      "description": "An evenly spaced set of continuous bins.",
      "required": [
        "type",
        "lower",
        "upper",
        "bins",
        "underflow",
        "overflow",
        "circular"
      ],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "regular" },
        "lower": { "type": "number", "description": "Lower edge of the axis." },
        "upper": { "type": "number", "description": "Upper edge of the axis." },
        "bins": {
          "type": "integer",
          "minimum": 0,
          "description": "Number of bins in the axis."
        },
        "underflow": {
          "type": "boolean",
          "description": "True if there is a bin for underflow."
        },
        "overflow": {
          "type": "boolean",
          "description": "True if there is a bin for overflow."
        },
        "circular": {
          "type": "boolean",
          "description": "True if the axis wraps around."
        },
        "metadata": { "$ref": "#/$defs/metadata" },
        "writer_info": { "$ref": "#/$defs/writer_info" }
      }
    },
    "variable_axis": {
      "type": "object",
      "description": "A variably spaced set of continuous bins.",
      "required": ["type", "edges", "underflow", "overflow", "circular"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "variable" },
        "edges": {
          "oneOf": [
            {
              "type": "array",
              "items": { "type": "number" },
              "minItems": 2,
              "uniqueItems": true
            },
            {
              "type": "string",
              "description": "A path (URI?) to the edges data."
            }
          ]
        },
        "underflow": { "type": "boolean" },
        "overflow": { "type": "boolean" },
        "circular": { "type": "boolean" },
        "metadata": { "$ref": "#/$defs/metadata" },
        "writer_info": { "$ref": "#/$defs/writer_info" }
      }
    },
    "category_str_axis": {
      "type": "object",
      "description": "A set of string categorical bins.",
      "required": ["type", "categories", "flow"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "category_str" },
        "categories": {
          "type": "array",
          "items": { "type": "string" },
          "uniqueItems": true
        },
        "flow": {
          "type": "boolean",
          "description": "True if flow bin (at the overflow position) present."
        },
        "metadata": { "$ref": "#/$defs/metadata" },
        "writer_info": { "$ref": "#/$defs/writer_info" }
      }
    },
    "category_int_axis": {
      "type": "object",
      "description": "A set of integer categorical bins in any order.",
      "required": ["type", "categories", "flow"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "category_int" },
        "categories": {
          "type": "array",
          "items": { "type": "integer" },
          "uniqueItems": true
        },
        "flow": {
          "type": "boolean",
          "description": "True if flow bin (at the overflow position) present."
        },
        "metadata": { "$ref": "#/$defs/metadata" },
        "writer_info": { "$ref": "#/$defs/writer_info" }
      }
    },
    "boolean_axis": {
      "type": "object",
      "description": "A simple true/false axis with no flow.",
      "required": ["type"],
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "boolean" },
        "metadata": { "$ref": "#/$defs/metadata" },
        "writer_info": { "$ref": "#/$defs/writer_info" }
      }
    },
    "int_storage": {
      "type": "object",
      "description": "A storage holding integer counts. Must be empty (only type), dense (type + values), or sparse (type + index + values).",
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "int" },
        "index": { "$ref": "#/$defs/sparse_array" },
        "values": { "$ref": "#/$defs/int_data_array" }
      },
      "oneOf": [
        { "required": ["type"], "maxProperties": 1 },
        { "required": ["type", "values"], "not": { "required": ["index"] } },
        { "required": ["type", "index", "values"] }
      ]
    },
    "double_storage": {
      "type": "object",
      "description": "A storage holding floating point counts. Must be empty (only type), dense (type + values), or sparse (type + index + values).",
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "double" },
        "index": { "$ref": "#/$defs/sparse_array" },
        "values": { "$ref": "#/$defs/data_array" }
      },
      "oneOf": [
        { "required": ["type"], "maxProperties": 1 },
        { "required": ["type", "values"], "not": { "required": ["index"] } },
        { "required": ["type", "index", "values"] }
      ]
    },
    "weighted_storage": {
      "type": "object",
      "description": "A storage holding floating point counts and variances. Must be empty, dense (type + values + variances), or sparse (type + index + values + variances).",
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "weighted" },
        "index": { "$ref": "#/$defs/sparse_array" },
        "values": { "$ref": "#/$defs/data_array" },
        "variances": { "$ref": "#/$defs/data_array" }
      },
      "oneOf": [
        { "required": ["type"], "maxProperties": 1 },
        {
          "required": ["type", "values", "variances"],
          "not": { "required": ["index"] }
        },
        { "required": ["type", "index", "values", "variances"] }
      ]
    },
    "mean_storage": {
      "type": "object",
      "description": "A storage holding 'profile'-style floating point counts, values, and variances. Must be empty, dense (type + counts + values + variances), or sparse (type + index + counts + values + variances).",
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "mean" },
        "index": { "$ref": "#/$defs/sparse_array" },
        "counts": { "$ref": "#/$defs/data_array" },
        "values": { "$ref": "#/$defs/data_array" },
        "variances": { "$ref": "#/$defs/data_array" }
      },
      "oneOf": [
        { "required": ["type"], "maxProperties": 1 },
        {
          "required": ["type", "counts", "values", "variances"],
          "not": { "required": ["index"] }
        },
        { "required": ["type", "index", "counts", "values", "variances"] }
      ]
    },
    "weighted_mean_storage": {
      "type": "object",
      "description": "A storage holding 'profile'-style floating point ∑weights, ∑weights², values, and variances. Must be empty, dense (all data fields), or sparse (index + all data fields).",
      "additionalProperties": false,
      "properties": {
        "type": { "type": "string", "const": "weighted_mean" },
        "index": { "$ref": "#/$defs/sparse_array" },
        "sum_of_weights": { "$ref": "#/$defs/data_array" },
        "sum_of_weights_squared": { "$ref": "#/$defs/data_array" },
        "values": { "$ref": "#/$defs/data_array" },
        "variances": { "$ref": "#/$defs/data_array" }
      },
      "oneOf": [
        { "required": ["type"], "maxProperties": 1 },
        {
          "required": [
            "type",
            "sum_of_weights",
            "sum_of_weights_squared",
            "values",
            "variances"
          ],
          "not": { "required": ["index"] }
        },
        {
          "required": [
            "type",
            "index",
            "sum_of_weights",
            "sum_of_weights_squared",
            "values",
            "variances"
          ]
        }
      ]
    }
  }
}

=== scikit-hep/uhi/tests/resources/valid_single/reg.json
{
  "uhi_schema": 1,
  "metadata": { "one": true, "two": 2, "three": "three" },
  "axes": [
    {
      "type": "regular",
      "lower": 0,
      "upper": 5,
      "bins": 3,
      "underflow": true,
      "overflow": true,
      "circular": false
    }
  ],
  "storage": { "type": "int", "values": [1, 2, 3, 4, 5] }
}
